
CREATE TEMP TABLE salaries_temp(
  prim_state char(2),
  area text,
  area_name text,
  occ_code text,
  occ_title text,
  occ_group text,
  tot_emp text,
  emp_prse decimal,
  jobs_1000 decimal,
  loc_quotient decimal,
  h_mean decimal,
  a_mean text,
  mean_prse decimal,
  h_pct10 decimal,
  h_pct25 decimal,
  h_median decimal,
  h_pct75 decimal,
  h_pct90 decimal,
  a_pct10 text,
  a_pct25 text,
  a_median text,
  a_pct75 text,
  a_pct90 text,
  annual bool,
  hourly bool
);

-- .CSV file generated via 'Save-As' from Excel.
COPY salaries_temp FROM '..\data\bls_salary_data\MSA_M2015_dl.orig-converted.no-headers.csv' DELIMITER ',' CSV;

CREATE TABLE salaries(
  prim_state char(2),
  area text,
  area_name text,
  occ_code text,
  occ_title text,
  occ_group text,
  tot_emp int,
  emp_prse decimal,
  jobs_1000 decimal,
  loc_quotient decimal,
  h_mean decimal,
  a_mean int,
  mean_prse decimal,
  h_pct10 decimal,
  h_pct25 decimal,
  h_median decimal,
  h_pct75 decimal,
  h_pct90 decimal,
  a_pct10 int,
  a_pct25 int,
  a_median int,
  a_pct75 int,
  a_pct90 int,
  annual bool,
  hourly bool
);

INSERT INTO salaries
  (prim_state,
  area,
  area_name,
  occ_code,
  occ_title,
  occ_group,
  tot_emp,
  emp_prse,
  jobs_1000,
  loc_quotient,
  h_mean,
  a_mean,
  mean_prse,
  h_pct10,
  h_pct25,
  h_median,
  h_pct75,
  h_pct90,
  a_pct10,
  a_pct25,
  a_median,
  a_pct75,
  a_pct90,
  annual,
  hourly)
SELECT
  prim_state,
  area,
  area_name,
  occ_code,
  occ_title,
  occ_group,
  translate(TOT_EMP, ',', '') :: int AS TOT_EMP,
  emp_prse,
  jobs_1000,
  loc_quotient,
  h_mean,
  translate(A_MEAN, ',', '') :: int AS A_MEAN,
  mean_prse,
  h_pct10,
  h_pct25,
  h_median,
  h_pct75,
  h_pct90,
  translate(a_pct10, ',', '') :: int AS a_pct10,
  translate(a_pct25, ',', '') :: int AS a_pct25,
  translate(a_median, ',', '') :: int AS a_median,
  translate(a_pct75, ',', '') :: int AS a_pct75,
  translate(a_pct90, ',', '') :: int AS a_pct90,
  annual,
  hourly
FROM salaries_temp;

